#!/usr/bin/env tsx
/**
 * Generate Supabase TypeScript types from the local database
 *
 * Usage: pnpm generate-types
 *
 * Prerequisites:
 * - Supabase local development must be running (supabase start)
 * - supabase CLI must be installed
 */

import { execSync } from 'node:child_process';
import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const OUTPUT_PATH = resolve(
  __dirname,
  '../../packages/providers/supabase/src/types/database.types.ts'
);

const SUPABASE_PROJECT_ID = 'local'; // Use 'local' for local development

async function generateTypes(): Promise<void> {
  console.log('🔄 Generating Supabase TypeScript types...\n');

  try {
    // Ensure the output directory exists
    mkdirSync(dirname(OUTPUT_PATH), { recursive: true });

    // Generate types using Supabase CLI
    const types = execSync(
      `supabase gen types typescript --local`,
      {
        encoding: 'utf-8',
        cwd: resolve(__dirname, '../..'),
      }
    );

    // Add header comment
    const header = `/**
 * This file is auto-generated by generate-types.ts
 * Do not edit this file manually
 *
 * Generated at: ${new Date().toISOString()}
 * Source: Local Supabase instance
 */

`;

    // Write the generated types
    writeFileSync(OUTPUT_PATH, header + types, 'utf-8');

    console.log(`✅ Types generated successfully!`);
    console.log(`📁 Output: ${OUTPUT_PATH}\n`);
  } catch (error) {
    console.error('❌ Failed to generate types:');

    if (error instanceof Error) {
      if (error.message.includes('supabase')) {
        console.error('\n💡 Make sure:');
        console.error('   1. Supabase CLI is installed: brew install supabase/tap/supabase');
        console.error('   2. Local Supabase is running: supabase start');
      }
      console.error('\nError:', error.message);
    }

    process.exit(1);
  }
}

generateTypes();

